services:
  test-back:
    container_name: test-back
    image: test-back:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - test-db
  test-db:
    container_name: test-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "dev_mem"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    ports:
      - 45533:5432